apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dothill-node-server
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: dynamic-provisionning-node
{{ include "dothill.labels" . | indent 4 }}

spec:
  selector:
    matchLabels:
      name: dothill-node-server
{{ include "dothill.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        name: dothill-node-server
{{ include "dothill.labels" . | indent 8 }}
    spec:
      hostNetwork: true
      hostIPC: true
      {{ if .Values.pspAdmissionControllerEnabled }}serviceAccount: csi-node-registrar{{ end }}
      {{- if .Values.nodeServer.nodeAffinity }}
      affinity:
        nodeAffinity:
{{ toYaml .Values.nodeServer.nodeAffinity | indent 10 }}
      {{- end }}
      {{- if .Values.nodeServer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeServer.nodeSelector | indent 8 }}
      {{- end }}
      containers:
        - name: dothill-node
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command:
            - dothill-node
            - -kubeletpath={{ .Values.kubeletPath }}
            - -bind=unix://{{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io/csi.sock
{{- include "dothill.extraArgs" .Values.node | indent 10 }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: plugin-dir
              mountPath: {{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io
            - name: mountpoint-dir
              mountPath: {{ .Values.kubeletPath }}/pods
              mountPropagation: Bidirectional
            - name: device-dir
              mountPath: /dev
            - name: iscsi-dir
              mountPath: /etc/iscsi
            - name: host
              mountPath: /host
              mountPropagation: Bidirectional
          ports:
          - containerPort: 9808
            name: healthz
            protocol: TCP
          - containerPort: 9842
            name: metrics
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            periodSeconds: 60
        - name: liveness-probe
          image: {{.Values.nodeLivenessProbe.image.repository }}:{{ .Values.nodeLivenessProbe.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
{{- include "dothill.extraArgs" .Values.nodeLivenessProbe | indent 10 }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
        - name: driver-registrar
          image: {{ .Values.csiNodeRegistrar.image.repository }}:{{ .Values.csiNodeRegistrar.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io/csi.sock
{{- include "dothill.extraArgs" .Values.csiNodeRegistrar | indent 10 }}
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      volumes:
        - name: registration-dir
          hostPath:
            path: {{ .Values.kubeletPath }}/plugins_registry/
        - name: mountpoint-dir
          hostPath:
            path: {{ .Values.kubeletPath }}/pods
        - name: plugin-dir
          hostPath:
            path: {{ .Values.kubeletPath }}/plugins/dothill.csi.enix.io
            type: DirectoryOrCreate
        - name: iscsi-dir
          hostPath:
            path: /etc/iscsi
        - name: device-dir
          hostPath:
            path: /dev
        - name: host
          hostPath:
            path: /